version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "metoffice-aws-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12bvctx1sqgkn"
s3_prefix = "metoffice-aws-lambda"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
